### ISSUE TITLE
Debian init.d script doesn't work with multiple domains

### ISSUE THREAD

**Issue by TeroPihlaja** [realityforge/chef-glassfish#102]
Looks like debian/ubuntu init.d script creation doesn't work correctly when multiple domains are defined.

Error message: "service glassfish already provided"

Looks like this is caused by this change 90384e94f3b1241a1f9c051dd342f1235c0c10d8

Fix would probably be to change
```# Provides:          glassfish```
to
```# Provides: glassfish-<%= @new_resource.domain_name %>```

Maybe we could copy all init info from master/templates/default/init.d.erb?

**Comment by realityforge** [comment]
Thanks for the heads up - fix applied!
