### ISSUE TITLE
Template domain.xml incldued in this recipe doesn't allow the start-domain command to work correctly

### ISSUE THREAD

**Issue by Riduidel** [realityforge/chef-glassfish#15]
I use my virtual glassfish server for testing (and easy distribution of the testing virtual machine) for various versions of my application.
In that context, I need to be able to create domains using my standard procedure, which involve calling the `start-domain` command from a `multimode`. When doing so, domain creation fail because glassfish don't know how to resolve the `CPU_NODE_COUNT` Chef recipe variable. (maybe because I call that recipe from Vagrant and don't set correctly the cpu count, I don't know). Furthermore, there are a lot of differences that could be handled through calls to `create-jvm-options`glassfish subcommands.

So. Is it possible to have this recipe create a glassfish instance where the domain.xml template file can be used to create working domains ?

**Comment by realityforge** [comment]
This has been addressed by removing the custom domain.xml from the cookbook and going back to using asadmin commands to set the jvm properties. 

So I am going to close this as I believe it has been addressed. Feel free to re-open if you feel otherwise.

Thanks again!
