### ISSUE TITLE
extra_libraries not downloading file from url

### ISSUE THREAD

**Issue by Natrinicle** [realityforge/chef-glassfish#41]
I have the following under the "wgu" domain in my role:
          "extra_libraries": {
            "ojdbc": {
              "type": "common",
              "url": "http://chefstore.wgu.edu/glassfish/ojdbc7-12.1.0.1.0.jar",
              "requires_restart": true
            }
          }

From the webserver:
chefstore /var/www/html/glassfish $ md5sum ojdbc7-12.1.0.1.0.jar 
b74ac7e10bbdde05dd03629788be2a1d  ojdbc7-12.1.0.1.0.jar
chefstore /var/www/html/glassfish $ du -sh ojdbc7-12.1.0.1.0.jar 
3.3M    ojdbc7-12.1.0.1.0.jar

From the glassfish client:
glassfish ~ $ md5sum /srv/glassfish/wgu/lib/ojdbc7-12.1.0.1.0.jar 
d41d8cd98f00b204e9800998ecf8427e  /srv/glassfish/wgu/lib/ojdbc7-12.1.0.1.0.jar
glassfish ~ $ du -sh /srv/glassfish/wgu/lib/ojdbc7-12.1.0.1.0.jar 
0       /srv/glassfish/wgu/lib/ojdbc7-12.1.0.1.0.jar

Running wget on http://chefstore.wgu.edu/glassfish/ojdbc7-12.1.0.1.0.jar gives me the correct file and allows Glassfish to start. The role for some reason doesn't download it though. Looking at the chef-client output, it says that it downloaded the file correctly:

  * glassfish_library[http://chefstore.wgu.edu/glassfish/ojdbc7-12.1.0.1.0.jar] action addRecipe: <Dynamically Defined Resource>
  * service[glassfish-wgu] action nothing (skipped due to action :nothing)
  * directory[/var/chef/cache/wgu_00f68c906f4a7af18c2d75945a0d8923f9725550] action create (up to date)
  * remote_file[/var/chef/cache/wgu_00f68c906f4a7af18c2d75945a0d8923f9725550/ojdbc7-12.1.0.1.0.jar] action create_if_missing (up to date)
  * bash[asadmin_add-library http://chefstore.wgu.edu/glassfish/ojdbc7-12.1.0.1.0.jar] action run
    - execute "bash"  "/tmp/chef-script20141017-17172-mejwj3"

**Comment by realityforge** [comment]
The immediate problem was addressed and will close this issue and open a new one for hash validation of libraries
