### ISSUE TITLE
Unable to debug

### ISSUE THREAD

**Issue by joaoces** [realityforge/chef-glassfish#43]
Hi,

First of all thanks for your hard work, second i'am just start using chef and vagrant.

My question is how can i setup the glassfish to enable debug? is it possible? I already checked the option under the server-config->JVM Settings but without success... I'am unable to debug the application, is there other way?

Best Regards
João

**Comment by realityforge** [comment]
As we are probably not going to directly address this. I cam going to close this issue. Feel free to re-open if you have a mechanism for fixing it.
