### ISSUE TITLE
Using the PKG took to Update / Extend a Glassfish install

### ISSUE THREAD

**Issue by sgreenslade** [realityforge/chef-glassfish#46]
Hi,

Has anyone tried using / scripting the glassfish pkg tool to update a Glassfish install?
What are the pros / cons?

From the documentation https://glassfish.java.net/docs/4.0/administration-guide.pdf  Ch11-5 it seems that this could be rather useful to keep Glassfish up-to date.... Or am I missing something?

Thanks

**Comment by realityforge** [comment]
There seems to be no interest in this issue. So I am closing it - feel free to re-open if it there is specific action required.
