### ISSUE TITLE
Versions in CHANGELOG.md

### ISSUE THREAD

**Issue by thorsten** [realityforge/chef-glassfish#51]
There are several versions mentioned in CHANGELOG.md which fix a lot of issues in v0.6.0. Are there any plans to tag those releases and make them available via supermarket.chef.io?

**Comment by realityforge** [comment]
Sorry for taking such a long time to reply but I have finally released 0.7.2. 

Hope that helps!

**Comment by thorsten** [comment]
Thanks!
