### ISSUE TITLE
How to use without deployables?

### ISSUE THREAD

**Issue by thorsten** [realityforge/chef-glassfish#53]
We want to use your recipe without using deployables. How to handle that? Didn't find anything in the documentation. Thanks for helping!

**Comment by realityforge** [comment]
It depends on what you mean by this. If you just supply a configuration that excludes deployables then no deployables will be deployed .... but it will also delete any existing applications already deployed to the server. (See https://github.com/realityforge/chef-glassfish-example/blob/master/Vagrantfile which has several configurations with no deployables). 

To avoid the "delete" step you will probably need to modify the ``attribute_driven_domain.rb`` recipe so skip the delete step. In theory I could add a configuration setting that indicated deployables were "unmanaged" so don't delete them and I have done similar things in other cookbooks to do just that. But that is not implemented at this stage.

**Comment by thorsten** [comment]
Currently we modified the attribute_driven_domain.rb file for our current needs. A configuration setting for unmanaged deployables would be awesome.

**Comment by realityforge** [comment]
Finally got around to addressing this. Thanks for the heads up and patience.

**Comment by thorsten** [comment]
Thank you!
