### ISSUE TITLE
Some Login module packages have been changed in Glassfish 4.x

### ISSUE THREAD

**Issue by ursNiemi** [realityforge/chef-glassfish#58]
In providers/domain.rb:
    'jdbcRealm' => 'com.sun.enterprise.security.auth.login.JDBCLoginModule',
    'jdbcDigestRealm' => 'com.sun.enterprise.security.auth.login.JDBCDigestLoginModule',
    'pamRealm' => 'com.sun.enterprise.security.auth.login.PamLoginModule',
for Glassfish 4.x , these should be:
    'jdbcRealm' => 'com.sun.enterprise.security.**ee**.auth.login.JDBCLoginModule',
    'jdbcDigestRealm' => 'com.sun.enterprise.security.**ee**.auth.login.JDBCDigestLoginModule',
    'pamRealm' => 'com.sun.enterprise.security.auth.**ee**.login.PamLoginModule',

**Comment by realityforge** [comment]
Thanks for highlighting this. I will try and address this in the future so that regardless of the GlassFish version the correct values are passed through

**Comment by realityforge** [comment]
#90 fixed this so closing the issue.

Thanks for the bug report
