### ISSUE TITLE
asenv.conf not updated appropriately

### ISSUE THREAD

**Issue by conoyes** [realityforge/chef-glassfish#64]
I found an inconsistency in the installed asenv config. When node['glassfish']['domains_dir'] is defined the asenv.conf file still contains the default domains path instead of the given parameter value:

> node['glassfish']['install_dir']}/glassfish/config/asenv.conf
```
...
AS_DEF_DOMAINS_PATH="../domains"
...
```
In my situation I think it should look like this:
```
...
AS_DEF_DOMAINS_PATH="/app/domains"
...
```

Maybe it is intentional, maybe it isn't. Please take my suggestion into consideration. Thanks! I'm using glassfish 0.7.4 BTW.

**Comment by realityforge** [comment]
Hi, It was not deliberately elided. It just was not ever used anywhere (i.e. the init scripts supply the correct parameters and we generate a script in bin/ of domain for scripting the domain and it supplies the correct parameters). There is no reason why it should not be configured as you suggest so I went and did it. If you could verify that it works for you, then that would be great.

**Comment by conoyes** [comment]
Will do it next week. Thanks.

**Comment by conoyes** [comment]
Great, d2d73db1c52cb0a0924c853bcaad419000dcfc04 fixed the issue. Thanks!
