### ISSUE TITLE
attribute_driven_domain.rb tries to create connection pool before deployment

### ISSUE THREAD

**Issue by conoyes** [realityforge/chef-glassfish#67]
Here's what's wrong with the [recipe](https://github.com/realityforge/chef-glassfish/blob/0.7.4/recipes/attribute_driven_domain.rb)'s resource usage.
* activemq-rar (JCA adapter) in `['glassfish']['domains']['app_domain']['deployables']`
* defined a connection pool and resource in `['glassfish']['domains']['app_domain']['resource_adapters']` for the adapter
* if I run the recipe from scratch, Chef fails with `STDERR: remote failure: Invalid raname. Connector Module with name activemq-rar not found.`
* if I have the domain in place, I deploy activemq-rar by hand and re-run the recipe, creating the connection pool succeeds

The RAR deployment should be done before creating a connection pool for it. I'll try to re-arrange the resources and see if it solves the problem.

**Comment by realityforge** [comment]
That is a problem. One way to fix it in the short term is to treat it like we treat osgi deployables and deploy it right at the start ahead of other deployables if it is a rar. The osgi deployables could be deployed, then the rars and then the process could continue as per normal.

The longer term solution that I am looking at is a way to globally order all the resources but that is still a while off.

**Comment by realityforge** [comment]
I believe this has been fixed by #69 - thanks!
