### ISSUE TITLE
Enhancement: endorsed package installation would be nice

### ISSUE THREAD

**Issue by conoyes** [realityforge/chef-glassfish#72]
It would be great if the cookbook could install [Java endorsed packages](https://docs.oracle.com/cd/E26576_01/doc.312/e24930/class-loaders.htm#GSDVG00097) as jar files into the Glassfish binary's `lib/endorsed` folder.

**Comment by realityforge** [comment]
I believe this has been fixed by #73 - thanks again for the contribution
