### ISSUE TITLE
JDBC statement timeout regex validation is invalid

### ISSUE THREAD

**Issue by conoyes** [realityforge/chef-glassfish#74]
Please see [asadmin documentation](http://docs.oracle.com/cd/E26576_01/doc.312/e24938/create-jdbc-connection-pool.htm#GSRFM00036)

The `statementtimeout` may be `-1` which disables this feature. This is the default value, but the user should be able to input this value explicitly. The value `-1` is invalid according to the resource attribute declaration: `resources/jdbc_connection_pool.rb`
```
def self.num(key, arg, default_value = 0)
  ATTRIBUTES << JdbcAttribute.new(key, :numeric, arg, default_value)
end

...

num(:statementleaktimeout, 'statement-leak-timeout-in-seconds')
```
This happens when I explicitly define the value `-1`:
```
ERROR: Option statementtimeout's value -1 does not match regular expression /^[0-9]+$/
```
```
# chef-solo --version
Chef: 11.18.12
# ruby --version
ruby 2.1.6p336 (2015-04-13 revision 50298) [x86_64-linux]
```

**Comment by realityforge** [comment]
That should be easy to fix. I wont have a chance to look in short term but will gladly accept pull requests ;)

**Comment by conoyes** [comment]
If I have the time, I'll look into it :+1:

**Comment by realityforge** [comment]
Great - thanks!

**Comment by realityforge** [comment]
Fixed I believe - thanks for reporting this
