### ISSUE TITLE
Bug: archives directory permission problem

### ISSUE THREAD

**Issue by conoyes** [realityforge/chef-glassfish#80]
The [deployable resource](https://github.com/realityforge/chef-glassfish/blob/master/providers/deployable.rb#L69) uses [realityforge/chef-archive project](https://github.com/realityforge/chef-archive)'s [default](https://github.com/realityforge/chef-archive/blob/master/resources/default.rb) resource. [This](https://github.com/realityforge/chef-archive/blob/master/resources/default.rb#L104) line determines the `base_directory` variable used by the [provider](https://github.com/realityforge/chef-archive/blob/master/providers/default.rb). [This](https://github.com/realityforge/chef-archive/blob/master/providers/default.rb#L54) line causes recursive directory creation. According to the [directory resource documentation](https://docs.chef.io/resource_directory.html#recursive-directories), the `owner`, `group` and `mode` variables are only applied to the leaf directory, but not the parents. Because of security/safety feature, the `glassfish` cookbook creates the directory `$DOMAIN_HOME/archives` with wrong ownership (and possibly only `root` umask controllable `rwx` permissions:
```
*****@*****:DOMAIN_HOME> ls -l
total 48
drwxr-xr-x 7 GLASSFISH_USER GLASSFISH_GROUP 4096 Feb 17 13:10 applications
drwxr-xr-x 5 root  root  4096 Feb 17 13:10 archives
drwxr-xr-x 4 GLASSFISH_USER GLASSFISH_GROUP 4096 Feb 17 13:07 autodeploy
...
```

**Comment by realityforge** [comment]
Yep - that looks like a bug and should be relatively easy to fix. Will try to have a look at it in the near future

**Comment by realityforge** [comment]
Working on addressing this...

**Comment by realityforge** [comment]
Fixed - thanks for reporting this.
