### ISSUE TITLE
Bug: login.conf permission problem

### ISSUE THREAD

**Issue by conoyes** [realityforge/chef-glassfish#81]
vanilla domain contains `config/login.conf` with permissions:
`-rw------- 1 USER GROUP 2497 Feb 18 14:54 config/login.conf`

cookbook creates it with these permissions:
`-r-------- 1 USER GROUP 561 Feb 18 14:42 config/login.conf`

[problem](https://github.com/realityforge/chef-glassfish/blob/master/providers/domain.rb#L241)

**Comment by realityforge** [comment]
Fixed I believe. Thanks for the heads up.

**Comment by conoyes** [comment]
Thanks!
