### ISSUE TITLE
lack of admin_port causes unwanted behavior with Glassfish 3.1.2.2

### ISSUE THREAD

**Issue by conoyes** [realityforge/chef-glassfish#87]
The cookbook issues commands with `... --port <empty> ...` which results in existing resource checking failure.

**Comment by realityforge** [comment]
Trying to figure out how you got this behaviour as the admin port is defined using something like `attribute :admin_port, :kind_of => Integer, :default => 4848` so you can not set it to anything other than an Integer and if unset defaults to 4848. So how are you producing this error.

**Comment by conoyes** [comment]
Umm, yeah You're right. I'll double check this one, may be my mistake.

**Comment by realityforge** [comment]
Closing this until there is enough details to reproduce
