### ISSUE TITLE
thread pool listing command not issued properly

### ISSUE THREAD

**Issue by conoyes** [realityforge/chef-glassfish#88]
Glassfish 4.0+: list-threadpools [doc](https://glassfish.java.net/docs/4.0/administration-guide.pdf), To List Thread Pools
Glassfish 3.1.2.2: list-threadpools [doc](http://docs.oracle.com/cd/E26576_01/doc.312/e24938/list-threadpools.htm)

[actual issued command: list-thread-pools](https://github.com/realityforge/chef-glassfish/blob/master/recipes/attribute_driven_domain.rb#L1354)

**Comment by realityforge** [comment]
Eep - looks like a problem. Simple fix - testing it now.

**Comment by realityforge** [comment]
Fixed - thanks for reporting this
